---
title: 【Swift】TCAのActionでVoidを使用するとエラーがでる
tags:
  - iOS
  - Swift
  - TCA
  - SwiftUI
private: false
updated_at: '2023-08-13T22:33:33+09:00'
id: 448fe0021978e8004c09
organization_url_name: avis-inc
slide: false
ignorePublish: false
---
# はじめに
最近、TCAを触ることが多くいろんな場面で躓くので記事にしていきます。

<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">TaskResult&lt;Void&gt;するとEquatableのエラーが出るんだけどどう対応したらいいのかわからん <a href="https://t.co/nEjZE97Kt0">pic.twitter.com/nEjZE97Kt0</a></p>&mdash; たいしん (@SNQ2001) <a href="https://twitter.com/SNQ2001/status/1690623565950005248?ref_src=twsrc%5Etfw">August 13, 2023</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

# 問題点
VoidがEquatableに準拠してないのでエラーが出る
![スクリーンショット 2023-08-13 22.29.47.png](https://qiita-image-store.s3.ap-northeast-1.amazonaws.com/0/1745371/fa87fa84-3b80-07b7-e5eb-b4f6c283b50d.png)


```swift
public enum Action: Equatable {
    case buttonTapped
    case sample(TaskResult<Void>)
}
```

# 回避策
```swift
public enum Action: Equatable {
    case buttonTapped
    case sample(TaskResult<EquatableVoid>)
    
    public enum EquatableVoid { case finished }
}
```

# 使い方
```swift
public enum Action: Equatable {
    case buttonTapped
    case sample(TaskResult<EquatableVoid>)

    public enum EquatableVoid { case finished }
}

public func reduce(into state: inout State, action: Action) -> Effect<Action> {
    switch action {
    case .buttonTapped:
        return .run { send in
             await send(.sample(TaskResult {
                try await Task.sleep(nanoseconds: 3 * NSEC_PER_SEC)
                return .finished
            }))
        }
    case let .sample(result):
        switch result {
        case .success:
            print("finished")
        case let .failure(error):
            print(error)
        }
        return .none
    }
}
```

# おわり
まじむずいです
